### ISSUE TITLE
Error using urlread The value of 'url' is invalid.

### ISSUE THREAD

**Issue by bohlinz** [APMonitor/apm_matlab#2]
Hi,

I try to solve an MPC problem with APM+ipopt. 
At the begining, the result seems right and after 14 iterations, it gives an error from Matlab as follow,

============================================
Error using urlread
The value of 'url' is invalid. Expected input to be one of these types:

char

Instead its type was java.net.URL.

Error in urlreadwrite>parseInputs (line 144)
p.parse(args{:})

Error in urlreadwrite (line 15)
inputs = parseInputs(fcn,varargin);

Error in urlread (line 47)
[s,status] = urlreadwrite(mfilename,catchErrors,url,varargin{:});

Error in urlread_apm (line 51)
    output = urlread(url);

Error in apm (line 31)
    response = urlread_apm(url);

Error in apm_load (line 37)
      response = apm(server,app,apm_block);

Error in apm_quadprog (line 271)
apm_load(s,a,'qp.apm');

========================================

could you help me to solve this problem? 
My Matlab version is 2018b

Many thanks in advance.

**Comment by bohlinz** [comment]
sorry, but I found the problem is outside of the solver. 
Thanks.

**Comment by bohlinz** [comment]
This problem is still there. And the crash iteration number is random.

**Comment by APMonitor** [comment]
Please check your IP address with https://apmonitor.com/ip.php This error can happen if your internet connection is intermittent, you have dual IP addresses, or if the server is unreliable. Could you try switching to server s='http://byu.apmonitor.com'  You can also run a local server and use s='http://127.0.0.1'  Installation instructions are here:  https://apmonitor.com/wiki/index.php/Main/APMonitorServer

**Comment by bohlinz** [comment]
The IP return by https://apmonitor.com/ip.php is 103.37.140.45.
And I switch to s='http://byu.apmonitor.com' instead of s = 'http://xps.apmonitor.com' it works.

Thanks!
