### ISSUE TITLE
Provide the gradient of the nonlinear constraint externally

### ISSUE THREAD

**Issue by haolee21** [APMonitor/apm_matlab#3]
I have a large scale optimization to solve (700 variables), which has around 1000 constraints (sparse). I wonder is it possible to provide the gradient of the constraint in matrix form to the solver? Otherwise, the solver will have to calculate itself.

**Comment by APMonitor** [comment]
Gekko doesn't allow for external gradients but does calculate sparse 1st and 2nd derivatives internally. You'll need to provide the model in Gekko form instead of calling an external black-box model.

**Comment by APMonitor** [comment]
Gekko can solve problems with 100,000+ variables so 700 shouldn't be a problem, especially if many of the constraints are linear.
